apiVersion: v2
name: user-chart
description: A Helm chart for Kubernetes

type: application

version: 0.7.0
appVersion: 0.0.1

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - user-database