"""Change user_account table structure

Revision ID: 26d7dd16fdc8
Revises: 79b32766a11d
Create Date: 2023-08-27 09:56:59.796764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26d7dd16fdc8'
down_revision: Union[str, None] = '79b32766a11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('user_name', sa.String(), nullable=False))
    op.add_column('user_account', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user_account', sa.Column('last_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user_account', ['user_name'])
    op.drop_column('user_account', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_account', type_='unique')
    op.drop_column('user_account', 'last_name')
    op.drop_column('user_account', 'first_name')
    op.drop_column('user_account', 'user_name')
    # ### end Alembic commands ###
