apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  DB_HOST: postgres
  DB_PORT: '5432'

---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
data:
  DB_NAME: dXNlci1kYg==
  DB_USER: dXNlcg==
  DB_PASSWORD: dXNlcg==