apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: user-ingress-helm
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ $.Release.Name }}-{{ include "user-chart.name" . }}
                port:
                  number: {{ .Values.ingress.port }}